# примеры API-запросов

@baseUrl = http://localhost:8000/api/v1

###

# создание продукта (сделано)
POST {{baseUrl}}/products/
Content-Type: application/json

{
  "title": "Арбуз",
  "description": "Оренбургский, холодок"
}

###

# получение продуктов (сделано)
GET {{baseUrl}}/products/?page=1
Content-Type: application/json

###

# обновление продукта (сделано)
PATCH {{baseUrl}}/products/2/
Content-Type: application/json

{
  "description": "Помидоры астраханские"
}

###

# удаление продукта (сделано)
DELETE {{baseUrl}}/products/9/


###

# поиск продуктов по названию и описанию (сделано)
GET {{baseUrl}}/products/?search=помидор
Content-Type: application/json

###

# просмотр складов (cделано)
GET {{baseUrl}}/stocks/
Content-Type: application/json

###

# удаление склада (сделано)
DELETE {{baseUrl}}/stocks/25/

###

# создание склада (сделано)
POST {{baseUrl}}/stocks/
Content-Type: application/json

{
  "address": "мой адрес не дом и не улица, мой адрес сегодня такой: www.ленинград-спб.ru3",
  "positions": [
    {
      "product": 2,
      "quantity": 250,
      "price": 120.50
    },
    {
      "product": 3,
      "quantity": 100,
      "price": 180
    }
  ]
}

###

# обновляем записи на складе
PATCH {{baseUrl}}/stocks/26/
Content-Type: application/json

{
  "positions": [
    {
      "product": 2,
      "quantity": 110,
      "price": 130.80
    },
    {
      "product": 3,
      "quantity": 243,
      "price": 145
    }
  ]
}

###

# поиск складов, где есть определенный продукт
GET {{baseUrl}}/stocks/?products=1
Content-Type: application/json
