# Generated by Django 4.2.5 on 2023-09-10 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_rename_teacher_teachers_remove_student_teacher_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Teachers',
            new_name='Teacher',
        ),
    ]
