# Generated by Django 4.2.4 on 2023-09-09 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('image', models.CharField(max_length=255, null=True)),
                ('price', models.IntegerField(null=True)),
                ('release_date', models.DateField(null=True)),
                ('lte_exist', models.BooleanField(null=True)),
                ('slug', models.CharField(max_length=55)),
            ],
        ),
    ]
