# Generated by Django 4.2.4 on 2023-09-04 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='image',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='phone',
            name='lte_exist',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='phone',
            name='price',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='phone',
            name='release_date',
            field=models.DateField(null=True),
        ),
    ]
