# Generated by Django 4.2.4 on 2023-09-05 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0003_alter_phone_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phone',
            name='id',
        ),
        migrations.AddField(
            model_name='phone',
            name='phone_id',
            field=models.CharField(default=1, max_length=50, primary_key=True, serialize=False, verbose_name='phone_id'),
            preserve_default=False,
        ),
    ]
