# Generated by Django 4.2.4 on 2023-09-05 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0004_remove_phone_id_phone_phone_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phone',
            name='phone_id',
        ),
        migrations.AddField(
            model_name='phone',
            name='id',
            field=models.BigAutoField(auto_created=True, default=None, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
