# Generated by Django 4.2.4 on 2023-09-21 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0003_alter_measurement_sensor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='description',
            field=models.TextField(max_length=500, null=True, verbose_name='Описание датчика'),
        ),
    ]
