# Generated by Django 4.2.4 on 2023-09-21 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0005_alter_sensor_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='description',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Описание датчика'),
        ),
    ]
