# Generated by Django 4.2.4 on 2023-09-21 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0007_alter_sensor_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='description',
            field=models.TextField(blank=True, default=None, max_length=500, verbose_name='Описание датчика'),
        ),
    ]
